### ISSUE TITLE
[Task] Gestion des notes perso

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/app-camping-des-speakers#10]
## Que doit-il être fait
Ajouter à la page de session la possibilité de créer des notes personnelles. Elle ne sont visibles que par l'utilisateur qui les créait.

## Cette tâche est-elle liée à une autre ?
Bloqué par #4

**Comment by gouz** [comment]
Openfeedback a été mis en place, je pense que cette notation n'est plus indispensable.

**Comment by taorepoara** [comment]
Selon moi, cette fonctionnalité n'a pas le même objectif qu'openfeedback. Il s'agit juste de créer des notes perso pour se souvenir de points clés des sessions.

**Comment by gouz** [comment]
Oups, désolé j'avais cru comprendre "Notation". En effet, ça peut être pratique ;)
