### ISSUE TITLE
[Task] Créer un fil d'Ariane

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/app-camping-des-speakers#2]
## Que doit-il être fait
Pour que les utilisateurs puisse s'y retrouver plus facilement dans l'application, créer un fil d’Ariane que l'on mettra en haut des pages sous le menu.

Dans ce fil d'Ariane, tous les éléments seront cliquables, sauf la page courante.

## Recommandation technique
Attention à la gestion des titres de pages qui seront affichés dans le fil d'Ariane.

**Comment by Elleriyc** [comment]
Bonjour je souhaiterais travailler dessus

**Comment by taorepoara** [comment]
Avec plaisir !
Je t'assigne la tâche. N'hésite à mettre des commentaires si tu as besoin d'aide

**Comment by Elleriyc** [comment]
Je veux bien quelques explications en plus sur ce que tu veux faire

**Comment by Elleriyc** [comment]
Au niveau du rendu final

**Comment by Elleriyc** [comment]
Est-ce qu'il y a une documentation avec les fonctions répertoriées de Lenra par hasard ?

**Comment by taorepoara** [comment]
Il n'y a rien de vraiment défini pour le style, mais le principe serait que quand on est dans une page on ait le fil d'Ariane correspondant:
- dans l'agenda: Agenda
- dans une session: Agenda (qui ramène à l'agenda) > Nom de la session
- dans la liste des speakers: Speakers
- dans la page d'un speaker: Speakers (qui ramène à la liste des speakers) > Nom du speaker
...

Il n'y a pas beaucoup de page, mais le système de route est toujours en alpha donc tu risque d'avoir des petits soucis, donc si tu as d'autres questions ou des problèmes techniques n'hésite pas :smiley:

**Comment by taorepoara** [comment]
@Elleriyc Nous avons pas mal avancé sur d'autres tâches de l'app. N'hésite pas à mettre à jour ton fork pour t'en inspirer ou à m'envoyer un DM sur Twitter: https://twitter.com/taorepoara

**Comment by taorepoara** [comment]
@Elleriyc nous voudrions mettre en place cette fonctionnalité pour lundi. Est-ce que tu penses que c'est jouable pour toi ou je reprends la tâche ? N'hésite pas si tu as besoin d'aide.

**Comment by taorepoara** [comment]
Désolé @Elleriyc , je vais reprendre la tâche pk on veut lancer la version ce matin.
