### ISSUE TITLE
[Task] Noter une session quand celle-ci est terminée

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/app-camping-des-speakers#5]
## Que doit-il être fait
Une fois qu'une conférence est terminée, permettre de la noter depuis la page session correspondante.

## Recommandation technique
Faire une note de 1 à 5 avec possibilité d'ajouter un commentaire.

## Cette tâche est-elle liée à une autre ?
Bloqué par #4

**Comment by taorepoara** [comment]
Voir si cette fonctionnalité est toujours d'actualité parce que ça pourrait faire doublons avec #22

**Comment by gouz** [comment]
Openfeedback a été mis en place, je pense que cette notation n'est plus indispensable.
