### ISSUE TITLE
[Task] Commentaires de sessions

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/app-camping-des-speakers#9]
## Que doit-il être fait
Permettre de commenter une session.
Les commentaires s'affichent sous forme d'un chat. La section de commentaire n'est accessible que 10 min avant le début d'une session et se ferme 1h après la session. (temps arbitraires, voir si on les garde comme ça).

## Recommandation technique
Utiliser un CRON pour activer/désactiver les commentaires.

## Préoccupations écologiques
Configurer le CRON pour qu'il ne fonctionne qu'aux heures nécessaires et que les jours correspondant au salon.

## Cette tâche est-elle liée à une autre ?
Bloqué par #4

**Comment by gouz** [comment]
Openfeedback a été mis en place, je pense que cette notation n'est plus indispensable.

Sur openfeedback il existe la notion de commentaire. Les speakers sont habitués à ça je pense que ça sera plus simple.
